// ============================================================
// KITCHENBAY — Complete Product Database (from KB 2.0 Excel)
// ============================================================

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;        // Base price excluding GST
  originalPrice: number; // MRP (crossed-out price)
  finalPrice: number;   // Sale price (what customer pays)
  discount: number;     // Discount percentage
  gstPercent: number;
  stock: number;
  category: string;     // kitchenware | dining | decor
  subcategory: string;  // e.g. cast-iron-cookwares
  material: string;     // Cast Iron | Stainless Steel | Soapstone | Brass | Copper | Bronze
  image: string;
  subImages?: string[];
  rating: number;
  reviewCount: number;
  featured: boolean;
  isActive?: boolean;
  sku?: string;
  height?: number;
  width?: number;
  length?: number;
  diameter?: number;
  weight?: number;
  sizeCategory?: string;
  tags?: string[];
  variants?: Record<string, { price: number; stock: number }>;
  attributes?: { name: string; value: string }[];
  brand?: string;
  shippingFee?: number;
  shippingMethod?: string;
}

export interface CartItem {
  product: Product;
  quantity: number;
  size?: string;
}

export interface Order {
  id: string;
  customer: string;
  email: string;
  date: string;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  items: CartItem[];
  subtotal: number;
  cgstAmount: number;
  sgstAmount: number;
  gstAmount: number;
  total: number;
  address: string;
  paymentMethod: string;
}

// ─── CATEGORIES ─────────────────────────────────────────────
export const categories = [
  { id: 'kitchenware', name: 'Kitchenware', icon: '🍳', count: 34 },
  { id: 'dining', name: 'Dining', icon: '🍽️', count: 13 },
  { id: 'brass-copper', name: 'Brass/Copper', icon: '🫕', count: 7 },
  { id: 'decor', name: 'Décor', icon: '🪔', count: 9 },
];

// ─── SUBCATEGORIES ───────────────────────────────────────────
export const subcategories = [
  // Kitchenware
  { id: 'cast-iron-cookwares', name: 'Cast Iron Cookwares', category: 'kitchenware', icon: '🥘' },
  { id: 'triply-cookwares', name: 'Triply Cookwares', category: 'kitchenware', icon: '🍲' },
  { id: 'soapstone-cookware', name: 'Soapstone Cookware', category: 'kitchenware', icon: '🪨' },
  { id: 'kitchen-food-storage', name: 'Kitchen / Food Storage', category: 'kitchenware', icon: '🫙' },
  { id: 'kitchen-accessories', name: 'Kitchen Accessories', category: 'kitchenware', icon: '🥄' },
  // Dining
  { id: 'coffee-tea-maker', name: 'Coffee & Tea Maker', category: 'dining', icon: '☕' },
  { id: 'tray-bowls', name: 'Tray & Bowls', category: 'dining', icon: '🥗' },
  { id: 'pitcher-cups-glass', name: 'Pitcher, Cups & Glass', category: 'dining', icon: '🥛' },
  { id: 'dining-plates', name: 'Dining Plates', category: 'dining', icon: '🍽️' },
  // Brass / Copper
  { id: 'brass-cookware', name: 'Brass Cookware', category: 'brass-copper', icon: '🍯' },
  { id: 'copper-cookware', name: 'Copper Cookware', category: 'brass-copper', icon: '🫖' },
  { id: 'brass-dining', name: 'Brass Dining & Serving', category: 'brass-copper', icon: '🥘' },
  { id: 'brass-copper-cookware', name: 'All Brass/Copper', category: 'brass-copper', icon: '🫕' },
  // Décor
  { id: 'lamp-diya', name: 'Lamp & Diya', category: 'decor', icon: '🪔' },
  { id: 'pooja-essentials', name: 'Pooja Essentials', category: 'decor', icon: '🪔' },
];

// ─── MATERIALS ───────────────────────────────────────────────
export const materials = [
  'Cast Iron',
  'Stainless Steel',
  'Soapstone',
  'Brass',
  'Copper',
  'Bronze',
];

// ─── PRODUCTS ────────────────────────────────────────────────
export const products: Product[] = [

  // ══════════════════════════════════════════════════════════
  // KITCHENWARE → Cast Iron Cookwares (12 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'ci-001',
    name: 'Cast Iron Appakal with Handle (Seasoned)',
    description: 'Premium seasoned cast iron appakal with ergonomic handle. Pre-seasoned with natural oil for non-stick cooking. Perfect for making authentic South Indian appam. Improves with use — becomes more non-stick over time. Suitable for gas, induction, and open fire cooking.',
    price: 677,
    originalPrice: 1699,
    finalPrice: 799,
    discount: 53,
    gstPercent: 18,
    stock: 45,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 238,
    featured: true,
  },
  {
    id: 'ci-002',
    name: 'Cast Iron Appakal (Seasoned) 9 Inch',
    description: 'Traditional 9-inch cast iron appakal, pre-seasoned and ready to use. Excellent heat retention for perfectly cooked appam. Lightweight design for easy handling. Naturally non-stick surface that improves with every use. Rust-resistant with proper care.',
    price: 592,
    originalPrice: 1599,
    finalPrice: 699,
    discount: 56,
    gstPercent: 18,
    stock: 38,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 185,
    featured: false,
  },
  {
    id: 'ci-003',
    name: 'Cast Iron Appakal (Seasoned) 8 Inch',
    description: 'Compact 8-inch seasoned cast iron appakal ideal for small families. Even heat distribution ensures golden-brown appam every time. Pre-seasoned with vegetable oil coating. Durable construction lasts generations. Easy to maintain and clean.',
    price: 550,
    originalPrice: 1499,
    finalPrice: 649,
    discount: 57,
    gstPercent: 18,
    stock: 52,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 142,
    featured: false,
  },
  {
    id: 'ci-004',
    name: 'Cast Iron Dosatawa with Handle (Seasoned)',
    description: 'Heavy-duty cast iron dosatawa with handle for making crispy dosas. Pre-seasoned surface ensures perfect non-stick cooking. Ideal for dosas, rotis, and pancakes. Superior heat retention gives restaurant-quality results at home. Compatible with all stovetops including induction.',
    price: 847,
    originalPrice: 1799,
    finalPrice: 999,
    discount: 44,
    gstPercent: 18,
    stock: 30,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1566454544259-f4b37690ca93?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 312,
    featured: true,
  },
  {
    id: 'ci-005',
    name: 'Cast Iron Mini Appam Pan (Seasoned) 4 Pits',
    description: '4-pit cast iron mini appam pan for making perfectly round appe and paniyarams. Pre-seasoned for immediate use. Each pit has uniform depth for consistent cooking. Suitable for making mini appams, appe, pancake bites, and more. Great for kids\' healthy snacks.',
    price: 1271,
    originalPrice: 2999,
    finalPrice: 1499,
    discount: 50,
    gstPercent: 18,
    stock: 25,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1585237017125-4b54d96a56a2?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 198,
    featured: false,
  },
  {
    id: 'ci-006',
    name: 'Cast Iron Mini Grill Pan (Seasoned)',
    description: 'Ridged cast iron grill pan for authentic grill marks on vegetables, paneer, and meats. Pre-seasoned surface prevents sticking. Raised ridges drain fat for healthier cooking. Excellent heat retention for even searing. Suitable for all heat sources.',
    price: 847,
    originalPrice: 1999,
    finalPrice: 999,
    discount: 50,
    gstPercent: 18,
    stock: 35,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 156,
    featured: false,
  },
  {
    id: 'ci-007',
    name: 'Cast Iron Premium Frypan (Seasoned)',
    description: 'Premium seasoned cast iron frypan for frying, sautéing, and deep-frying. Pre-seasoned coating for non-stick performance. Deep sides prevent oil splatter. Superior heat distribution eliminates hot spots. Oven-safe up to 500°F. A kitchen essential that improves with every use.',
    price: 677,
    originalPrice: 1499,
    finalPrice: 799,
    discount: 47,
    gstPercent: 18,
    stock: 40,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1648047596427-11f3a7e8be7a?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 267,
    featured: true,
  },
  {
    id: 'ci-008',
    name: 'Cast Iron Premium Paniyaarakal (Seasoned) 9 Pits',
    description: '9-pit premium cast iron paniyaarakal for making traditional kuzhipaniyaram. Pre-seasoned for non-stick cooking. Each pit ensures uniform cooking. Perfect for making appe, paniyaram, and mini desserts. Thick walls provide excellent heat retention.',
    price: 1186,
    originalPrice: 2499,
    finalPrice: 1399,
    discount: 44,
    gstPercent: 18,
    stock: 28,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 189,
    featured: true,
  },
  {
    id: 'ci-009',
    name: 'Cast Iron Premium Paniyaarakal (Seasoned) 14 Pits',
    description: 'Extra-large 14-pit cast iron paniyaarakal for catering and large families. More pits mean faster cooking for parties. Pre-seasoned surface for non-stick results. Makes perfectly shaped round snacks every time. Durable and will last for decades.',
    price: 1440,
    originalPrice: 2999,
    finalPrice: 1699,
    discount: 43,
    gstPercent: 18,
    stock: 20,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 134,
    featured: false,
  },
  {
    id: 'ci-010',
    name: 'Cast Iron Saucepan (Seasoned)',
    description: 'Deep cast iron saucepan for curries, gravies, and stews. Pre-seasoned interior for natural non-stick cooking. Thick base ensures slow, even cooking that enhances flavour. Suitable for all stovetops including induction. Long handle for safe pouring.',
    price: 932,
    originalPrice: 1999,
    finalPrice: 1099,
    discount: 45,
    gstPercent: 18,
    stock: 32,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 211,
    featured: false,
  },
  {
    id: 'ci-011',
    name: 'Cast Iron Skillet (Seasoned) 10 Inch',
    description: '10-inch cast iron skillet, the most versatile pan in any kitchen. Pre-seasoned with vegetable oil for a natural non-stick surface. Perfect for searing, baking, frying, and braising. Ideal for stovetop-to-oven cooking. Develops a better non-stick surface with each use.',
    price: 847,
    originalPrice: 1999,
    finalPrice: 999,
    discount: 50,
    gstPercent: 18,
    stock: 55,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1581781870027-04212e231e50?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 445,
    featured: true,
  },
  {
    id: 'ci-012',
    name: 'Cast Iron Tadka Pan (Seasoned)',
    description: 'Small cast iron tadka pan for making perfect tempering/tadka. Pre-seasoned for immediate use. Deep design prevents oil spillage during tempering. Retains heat longer for efficient tadka. Essential for South Indian and North Indian cooking. Easy to use and clean.',
    price: 423,
    originalPrice: 999,
    finalPrice: 499,
    discount: 50,
    gstPercent: 18,
    stock: 80,
    category: 'kitchenware',
    subcategory: 'cast-iron-cookwares',
    material: 'Cast Iron',
    image: 'https://images.unsplash.com/photo-1612871689836-c45d58e68a0d?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 178,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // KITCHENWARE → Triply Cookwares (10 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'tc-001',
    name: 'Platinum Triply Stainless Steel Casserole/Biryani Pot 24cm',
    description: 'Professional-grade triply stainless steel casserole with three layers — stainless steel, aluminium core, stainless steel. 24cm capacity perfect for biryani and large curries. Even heat distribution prevents burning. Dishwasher safe. Induction compatible. Mirror finish exterior.',
    price: 1610,
    originalPrice: 2999,
    finalPrice: 1899,
    discount: 37,
    gstPercent: 18,
    stock: 30,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 156,
    featured: false,
  },
  {
    id: 'tc-002',
    name: 'Platinum Triply Stainless Steel Casserole/Biryani Pot 28cm',
    description: 'Large 28cm triply stainless steel casserole for big families and parties. Three-ply construction ensures uniform heating. Perfect for biryani, pasta, soups, and large batches. Stainless steel lid included. Oven safe up to 500°F. Easy-grip handles for safe pouring.',
    price: 1779,
    originalPrice: 3399,
    finalPrice: 2099,
    discount: 38,
    gstPercent: 18,
    stock: 22,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 123,
    featured: true,
  },
  {
    id: 'tc-003',
    name: 'Platinum Triply Stainless Steel Frypan 1700ml/2100ml',
    description: 'Premium triply frypan with 1700ml–2100ml capacity. Three-layer construction distributes heat perfectly. Suitable for frying, sautéing, and making omelettes. Riveted handles for durability. Compatible with all cooktops including induction. Scratch-resistant surface.',
    price: 1101,
    originalPrice: 2299,
    finalPrice: 1299,
    discount: 43,
    gstPercent: 18,
    stock: 35,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1648047596427-11f3a7e8be7a?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 198,
    featured: false,
  },
  {
    id: 'tc-004',
    name: 'Platinum Triply Stainless Steel Frypan 900ml/1300ml',
    description: 'Compact triply frypan for individuals and small families. 900ml–1300ml capacity perfect for everyday cooking. Even heat distribution without hot spots. Ergonomic handle stays cool during cooking. Polished interior for easy cleaning. Works on gas, electric, and induction.',
    price: 974,
    originalPrice: 1999,
    finalPrice: 1149,
    discount: 43,
    gstPercent: 18,
    stock: 48,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 167,
    featured: false,
  },
  {
    id: 'tc-005',
    name: 'Platinum Triply Stainless Steel Kadai Large',
    description: 'Large triply stainless steel kadai for deep frying and cooking large batches. Thick aluminium core between steel layers ensures perfect heat distribution. Wide base for efficient cooking. High sides prevent oil splatter. Suitable for all stovetops. Easy to clean polished surface.',
    price: 1694,
    originalPrice: 3099,
    finalPrice: 1999,
    discount: 35,
    gstPercent: 18,
    stock: 25,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 213,
    featured: true,
  },
  {
    id: 'tc-006',
    name: 'Platinum Triply Stainless Steel Tops Large',
    description: 'Large triply stainless steel tops (pressure cooker style pot) for fast cooking. Three-layer sandwich construction for energy efficiency. Perfect for rice, dal, and large quantities. Whistle-free design. Tempered glass lid for safe monitoring. Induction compatible.',
    price: 1694,
    originalPrice: 3249,
    finalPrice: 1999,
    discount: 38,
    gstPercent: 18,
    stock: 18,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 142,
    featured: false,
  },
  {
    id: 'tc-007',
    name: 'Platinum Triply Stainless Steel Tops Medium',
    description: 'Medium triply stainless steel tops for everyday cooking. Perfect capacity for 2–4 people. Three-layer construction for superior heat performance. Ergonomic side handles for safe carrying. Polished mirror finish inside and out. Dishwasher safe.',
    price: 1271,
    originalPrice: 2299,
    finalPrice: 1499,
    discount: 35,
    gstPercent: 18,
    stock: 30,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 128,
    featured: false,
  },
  {
    id: 'tc-008',
    name: 'Platinum Triply Stainless Steel Tops Small',
    description: 'Compact triply stainless steel tops ideal for singles and couples. Small but mighty — three-layer construction provides excellent heat management. Great for making milk, heating soups, or preparing small portions. Lightweight and easy to handle. Budget-friendly premium cookware.',
    price: 847,
    originalPrice: 1699,
    finalPrice: 999,
    discount: 41,
    gstPercent: 18,
    stock: 42,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1566454544259-f4b37690ca93?w=600&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewCount: 95,
    featured: false,
  },
  {
    id: 'tc-009',
    name: 'Platinum Triply Stainless Steel Wokpan 1500ml/2100ml',
    description: 'Premium triply wokpan for stir-frying and Asian cooking. 1500ml–2100ml capacity for versatile cooking. High sides and round bottom for easy tossing. Three-layer construction ensures uniform high-heat cooking. Flat base for stability on all cooktops. Long ergonomic handle.',
    price: 1059,
    originalPrice: 2299,
    finalPrice: 1249,
    discount: 46,
    gstPercent: 18,
    stock: 28,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 176,
    featured: false,
  },
  {
    id: 'tc-010',
    name: 'Platinum Triply Stainless Steel Wokpan 800ml/1100ml',
    description: 'Small triply wokpan for quick stir-fries and sautéing. 800ml–1100ml size perfect for single servings. Triply construction provides quick, even heating. Lightweight and easy to manoeuvre. Suitable for gas and induction cooktops. Mirror polished finish for easy cleaning.',
    price: 804,
    originalPrice: 1699,
    finalPrice: 949,
    discount: 44,
    gstPercent: 18,
    stock: 40,
    category: 'kitchenware',
    subcategory: 'triply-cookwares',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1612871689836-c45d58e68a0d?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 112,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // KITCHENWARE → Soapstone Cookware (6 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'ss-001',
    name: 'Soapstone/Kalchatti Dosakal/Tawa (Treated)',
    description: 'Authentic soapstone/kalchatti dosa tawa, treated and ready to use. Naturally non-stick mineral surface requires zero oil. Keeps food warm long after cooking. Alkaline nature neutralises food acidity. Infuses minerals like calcium and magnesium into food. A healthy cooking choice passed down through generations.',
    price: 1016,
    originalPrice: 1600,
    finalPrice: 1199,
    discount: 25,
    gstPercent: 18,
    stock: 20,
    category: 'kitchenware',
    subcategory: 'soapstone-cookware',
    material: 'Soapstone',
    image: 'https://images.unsplash.com/photo-1584990347449-a5d9f800a783?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 134,
    featured: true,
  },
  {
    id: 'ss-002',
    name: 'Soapstone/Kalchatti Kadai (Treated) Small',
    description: 'Small treated soapstone kadai for everyday frying and sautéing. Alkaline minerals in the stone balance food pH naturally. Zero chemical coating — 100% natural and safe. Slow heat absorption gives food a rich, deep flavour. Handcrafted by traditional Kitchenbays in Tamil Nadu.',
    price: 1355,
    originalPrice: 2400,
    finalPrice: 1599,
    discount: 33,
    gstPercent: 18,
    stock: 15,
    category: 'kitchenware',
    subcategory: 'soapstone-cookware',
    material: 'Soapstone',
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 98,
    featured: false,
  },
  {
    id: 'ss-003',
    name: 'Soapstone/Kalchatti Paniyaarakal 10 Pits (Treated)',
    description: '10-pit soapstone paniyaarakal for making healthy kuzhipaniyaram. No artificial coating — pure stone cooking. Adds beneficial minerals to your food. Each pit is hand-carved for uniform depth. Perfect non-stick cooking with minimal oil. Slow, gentle cooking enhances taste.',
    price: 931,
    originalPrice: 1700,
    finalPrice: 1099,
    discount: 35,
    gstPercent: 18,
    stock: 18,
    category: 'kitchenware',
    subcategory: 'soapstone-cookware',
    material: 'Soapstone',
    image: 'https://images.unsplash.com/photo-1585237017125-4b54d96a56a2?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 86,
    featured: false,
  },
  {
    id: 'ss-004',
    name: 'Soapstone/Kalchatti Pot (Treated) Small',
    description: 'Small treated soapstone pot for cooking curries, soups, and gravies. Natural stone cooking enhances the authentic taste of traditional recipes. Maintains temperature for longer than metal pots. Rich in minerals — food cooked in it absorbs calcium and magnesium. Eco-friendly and chemical-free.',
    price: 1355,
    originalPrice: 2500,
    finalPrice: 1599,
    discount: 36,
    gstPercent: 18,
    stock: 12,
    category: 'kitchenware',
    subcategory: 'soapstone-cookware',
    material: 'Soapstone',
    image: 'https://images.unsplash.com/photo-1612871689836-c45d58e68a0d?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 112,
    featured: false,
  },
  {
    id: 'ss-005',
    name: 'Soapstone/Kalchatti Pot (Treated) Medium',
    description: 'Medium soapstone pot suitable for families of 4–6 people. Slow cooking in soapstone brings out the best flavours in dals, rasam, and curries. Naturally alkaline stone improves food quality. Each pot is unique — handcrafted with minor natural variations. Eco-friendly cooking at its finest.',
    price: 1779,
    originalPrice: 3150,
    finalPrice: 2099,
    discount: 33,
    gstPercent: 18,
    stock: 10,
    category: 'kitchenware',
    subcategory: 'soapstone-cookware',
    material: 'Soapstone',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 78,
    featured: true,
  },
  {
    id: 'ss-006',
    name: 'Soapstone/Kalchatti Pot (Treated) Large',
    description: 'Large soapstone pot for big families and special occasions. Premium quality soapstone sourced from natural quarries. Treated to prevent cracking during cooking. Ideal for making sambar, rasam, biriyani, and traditional dishes. Maintains heat remarkably well. An heirloom-quality cooking vessel.',
    price: 2118,
    originalPrice: 3500,
    finalPrice: 2499,
    discount: 29,
    gstPercent: 18,
    stock: 8,
    category: 'kitchenware',
    subcategory: 'soapstone-cookware',
    material: 'Soapstone',
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 64,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // KITCHENWARE → Kitchen / Food Storage (4 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'kfs-001',
    name: 'Stainless Steel Canister/Storage Container Set of 3',
    description: 'Set of 3 premium stainless steel canisters in graduated sizes. Airtight lids keep food fresh for longer. BPA-free and food-grade stainless steel. Mirror finish exterior adds elegance to your kitchen countertop. Stackable design saves space. Perfect for flour, sugar, tea, coffee, and dry goods.',
    price: 635,
    originalPrice: 1199,
    finalPrice: 749,
    discount: 38,
    gstPercent: 18,
    stock: 60,
    category: 'kitchenware',
    subcategory: 'kitchen-food-storage',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb13?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 198,
    featured: false,
  },
  {
    id: 'kfs-002',
    name: 'Stainless Steel Elegant Transparent Masala/Spice Box Large',
    description: 'Large transparent masala box with 7 compartments in a single steel tray. Clear lid lets you see all spices at once. Removable inner containers for easy cleaning. Premium stainless steel base with airtight seal. Includes a tiny spoon for each compartment. Keeps spices organised and fresh.',
    price: 762,
    originalPrice: 1699,
    finalPrice: 899,
    discount: 47,
    gstPercent: 18,
    stock: 45,
    category: 'kitchenware',
    subcategory: 'kitchen-food-storage',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 234,
    featured: true,
  },
  {
    id: 'kfs-003',
    name: 'Stainless Steel Elegant Curve Tops Set of 4 Pcs',
    description: 'Set of 4 stainless steel curve-top containers (tops) in different sizes. Elegant curved design adds aesthetic appeal to your kitchen. Premium food-grade steel with mirror finish. Tight-fitting lids seal in freshness. Nested for compact storage. Dishwasher safe and rust-resistant.',
    price: 677,
    originalPrice: 1399,
    finalPrice: 799,
    discount: 43,
    gstPercent: 18,
    stock: 38,
    category: 'kitchenware',
    subcategory: 'kitchen-food-storage',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 156,
    featured: false,
  },
  {
    id: 'kfs-004',
    name: 'Stainless Steel Karaikodi Tops Set of 4 Pcs',
    description: 'Set of 4 traditional Karaikodi-style stainless steel tops with distinctive design. High-quality food-grade stainless steel. Airtight lids preserve food freshness. Perfect for storing curd, pickles, and leftovers. Traditional South Indian kitchen staple in premium form. Easy to clean and maintain.',
    price: 847,
    originalPrice: 1699,
    finalPrice: 999,
    discount: 41,
    gstPercent: 18,
    stock: 42,
    category: 'kitchenware',
    subcategory: 'kitchen-food-storage',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewCount: 123,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // KITCHENWARE → Kitchen Accessories (2 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'ka-001',
    name: 'Premium Food Serving/Cooking Ladles Set of 4 Pcs',
    description: 'Set of 4 premium cooking and serving ladles in different sizes. Comfortable grip handle. Suitable for serving rice, dal, sambar, and curries. Heat-resistant handle prevents burning. Hygienic food-grade material. Elegant and functional kitchen accessories. Easy to clean and store.',
    price: 338,
    originalPrice: 499,
    finalPrice: 399,
    discount: 20,
    gstPercent: 18,
    stock: 90,
    category: 'kitchenware',
    subcategory: 'kitchen-accessories',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1593113630400-ea4288922497?w=600&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewCount: 312,
    featured: false,
  },
  {
    id: 'ka-002',
    name: 'Premium Stainless Steel Serving/Cooking Turner Ladles Set of 4 Pcs',
    description: 'Set of 4 premium stainless steel turner/ladle set including spatula, serving spoon, slotted spoon, and ladle. Mirror polished finish. Ergonomic handles for comfortable use. Food-grade stainless steel — rust resistant and hygienic. Hook ends for hanging storage. Dishwasher safe.',
    price: 381,
    originalPrice: 699,
    finalPrice: 449,
    discount: 36,
    gstPercent: 18,
    stock: 75,
    category: 'kitchenware',
    subcategory: 'kitchen-accessories',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 278,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // DINING → Coffee & Tea Maker (2 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'ct-001',
    name: 'Pure Brass Coffee Dabara Set of 4 Pcs',
    description: 'Authentic South Indian brass coffee dabara set — includes 4 tumblers and 4 davaras. Traditional way to serve filter coffee. Brass keeps coffee warm longer. Elegant vintage look that enhances the coffee experience. Set of 4 complete units. A must-have for filter coffee lovers.',
    price: 762,
    originalPrice: 1499,
    finalPrice: 899,
    discount: 40,
    gstPercent: 18,
    stock: 35,
    category: 'brass-copper',
    subcategory: 'brass-dining',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 324,
    featured: true,
  },
  {
    id: 'ct-002',
    name: 'Stainless Steel Polish Vintage Coffee Filter',
    description: 'Traditional South Indian stainless steel coffee filter for authentic drip coffee. Available in size 2 (2-cup). Mirror-polished finish. Two-chamber design — upper for coffee powder, lower for brewed coffee. Preserves natural coffee oils for rich flavour. Easy to clean. A timeless kitchen classic.',
    price: 253,
    originalPrice: 399,
    finalPrice: 299,
    discount: 25,
    gstPercent: 18,
    stock: 65,
    category: 'dining',
    subcategory: 'coffee-tea-maker',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1603566164673-8a3c874bc0b3?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 456,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // DINING → Tray & Bowls (1 product)
  // ══════════════════════════════════════════════════════════
  {
    id: 'tb-001',
    name: 'Stainless Steel Mirror Finish Rice Plate (Kumcha)',
    description: 'Classic stainless steel kumcha/rice plate with mirror finish. Ideal for everyday serving. Durable food-grade stainless steel. Easy to clean. Traditional South Indian thali-style serving plate. Rust-resistant and long-lasting. Suitable for serving rice, curries, and full meals.',
    price: 211,
    originalPrice: 350,
    finalPrice: 249,
    discount: 29,
    gstPercent: 18,
    stock: 100,
    category: 'dining',
    subcategory: 'tray-bowls',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1603180811123-885c8b18f3a8?w=600&auto=format&fit=crop&q=80',
    rating: 4.1,
    reviewCount: 189,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // DINING → Pitcher, Cups & Glass (5 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'pcg-001',
    name: 'Chotta Bheem Printed Straw Tumbler with Lid',
    description: 'Colourful Chotta Bheem printed straw tumbler with secure lid. BPA-free food-grade material. Perfect for children. Includes reusable straw. Fun cartoon design kids will love. Easy to carry to school. Leak-proof lid. Dishwasher safe. Encourages children to drink more water.',
    price: 191,
    originalPrice: 299,
    finalPrice: 225,
    discount: 25,
    gstPercent: 18,
    stock: 120,
    category: 'dining',
    subcategory: 'pitcher-cups-glass',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewCount: 234,
    featured: false,
  },
  {
    id: 'pcg-002',
    name: 'Pure Copper Vintage Mat Tumbler Set of 6 Pcs',
    description: 'Elegant set of 6 pure copper vintage matte-finish tumblers. Drinking from copper vessels is an ancient Ayurvedic practice — water stored overnight absorbs beneficial minerals. Handcrafted vintage design. Each tumbler is unique. Anti-microbial properties keep water fresh. Perfect gifting set.',
    price: 1271,
    originalPrice: 1999,
    finalPrice: 1499,
    discount: 25,
    gstPercent: 18,
    stock: 28,
    category: 'dining',
    subcategory: 'pitcher-cups-glass',
    material: 'Copper',
    image: 'https://images.unsplash.com/photo-1610393221976-654dbdbb242e?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 198,
    featured: true,
  },
  {
    id: 'pcg-003',
    name: 'Pure Copper Water Jug | Premium Luxury Line with Copper Lid',
    description: 'Luxurious pure copper water jug with matching copper lid. Premium luxury finish with elegant line engravings. Store water overnight and drink in the morning for Ayurvedic health benefits. Copper\'s natural anti-bacterial properties keep water fresh. Stunning centrepiece for any dining table.',
    price: 847,
    originalPrice: 1849,
    finalPrice: 999,
    discount: 46,
    gstPercent: 18,
    stock: 22,
    category: 'dining',
    subcategory: 'pitcher-cups-glass',
    material: 'Copper',
    image: 'https://images.unsplash.com/photo-1531685250784-7569952593d2?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 267,
    featured: true,
  },
  {
    id: 'pcg-004',
    name: 'Stainless Steel Laser Designer Tumbler Set of 6 Pcs',
    description: 'Set of 6 stainless steel tumblers with intricate laser-cut designer patterns. Elegant patterns that catch light beautifully. Food-grade stainless steel — rust-proof and durable. Double-walled design maintains temperature. Perfect for serving water, juice, or lassi at special occasions.',
    price: 592,
    originalPrice: 990,
    finalPrice: 699,
    discount: 29,
    gstPercent: 18,
    stock: 45,
    category: 'dining',
    subcategory: 'pitcher-cups-glass',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 178,
    featured: false,
  },
  {
    id: 'pcg-005',
    name: 'Stainless Steel Matt Finish Designer Tumbler Set of 6 Pcs',
    description: 'Set of 6 stainless steel tumblers with sophisticated matte finish. Contemporary design suits modern dining setups. Premium food-grade steel. Fingerprint-resistant matte coating. Perfect for everyday and formal use. Easy to clean. Elegant gifting option for housewarming and weddings.',
    price: 550,
    originalPrice: 990,
    finalPrice: 649,
    discount: 34,
    gstPercent: 18,
    stock: 52,
    category: 'dining',
    subcategory: 'pitcher-cups-glass',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1603566164673-8a3c874bc0b3?w=600&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 145,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // BRASS/COPPER → All Brass/Copper (3 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'bcc-001',
    name: 'Pure Brass Pongal Panai/Theksa with Lid (Tin Coated)',
    description: 'Traditional pure brass pongal pot with tin coating inside for safe cooking. Perfect for making pongal, payasam, and festive dishes. Tin coating prevents brass-food reaction while retaining heat properties. Traditional cooking vessel used in Tamil Nadu for generations. Ideal for Pongal festival cooking.',
    price: 1949,
    originalPrice: 2999,
    finalPrice: 2299,
    discount: 23,
    gstPercent: 18,
    stock: 15,
    category: 'brass-copper',
    subcategory: 'brass-cookware',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 89,
    featured: true,
  },
  {
    id: 'bcc-002',
    name: 'Pure Brass Pongal Uruli/Pot with Lid (Tin Coated)',
    description: 'Wide-mouth pure brass uruli/pot with tin coating for safe food preparation. Traditional Kerala and Tamil Nadu cooking vessel. Ideal for making payasam, pradaman, and sweet dishes. Tin coating inside prevents any brass-food chemical interaction. Authentic heirloom design.',
    price: 1779,
    originalPrice: 2899,
    finalPrice: 2099,
    discount: 28,
    gstPercent: 18,
    stock: 12,
    category: 'brass-copper',
    subcategory: 'brass-cookware',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1610393221976-654dbdbb242e?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 72,
    featured: false,
  },
  {
    id: 'bcc-003',
    name: 'Pure Copper Pongal Panai/Theksa with Lid (Tin Coated)',
    description: 'Authentic pure copper pongal pot with protective tin coating. Premium copper construction with superior heat conductivity. Tin coating inside ensures safe cooking. Traditional design used in temple cooking across South India. Makes the most authentic tasting pongal. A prized heirloom piece.',
    price: 2203,
    originalPrice: 3899,
    finalPrice: 2599,
    discount: 33,
    gstPercent: 18,
    stock: 10,
    category: 'brass-copper',
    subcategory: 'copper-cookware',
    material: 'Copper',
    image: 'https://images.unsplash.com/photo-1531685250784-7569952593d2?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 56,
    featured: false,
  },

  // ══════════════════════════════════════════════════════════
  // DINING → Dining Plates (2 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'dp-001',
    name: 'Stainless Steel Mirror Finish Rice Plate (Kumcha)',
    description: 'Premium stainless steel rice plate with mirror-polished finish. Classic South Indian style serving plate. Ideal for serving complete meals. Food-grade stainless steel — hygienic and durable. Easy to clean and maintain. Rust-resistant and long-lasting. Traditional Indian thali experience.',
    price: 211,
    originalPrice: 350,
    finalPrice: 249,
    discount: 29,
    gstPercent: 18,
    stock: 100,
    category: 'dining',
    subcategory: 'dining-plates',
    material: 'Stainless Steel',
    image: 'https://images.unsplash.com/photo-1603180811123-885c8b18f3a8?w=600&auto=format&fit=crop&q=80',
    rating: 4.1,
    reviewCount: 167,
    featured: false,
  },
  {
    id: 'dp-002',
    name: 'Pure Bronze Kansa Thali / Plate',
    description: 'Traditional pure Kansa (bell metal bronze) thali — the Ayurvedic metal plate. Kansa/bronze is known to be auspicious and health-promoting. Alkaline metal that neutralises food acidity. Destroys harmful bacteria. Improves digestion. Handcrafted by skilled Kitchenbays. A true heirloom piece that gets better with age.',
    price: 3898,
    originalPrice: 5900,
    finalPrice: 4600,
    discount: 22,
    gstPercent: 18,
    stock: 8,
    category: 'dining',
    subcategory: 'dining-plates',
    material: 'Bronze',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 45,
    featured: true,
  },

  // ══════════════════════════════════════════════════════════
  // DÉCOR → Lamp & Diya (8 products)
  // ══════════════════════════════════════════════════════════
  {
    id: 'ld-001',
    name: 'Brass Kapoor Dani & Camphor Lamp/Traditional Diya',
    description: 'Elegant pure brass camphor lamp (kapoor dani) for daily puja. Traditional design with intricate carvings. Brass construction ensures durability. Perfect for lighting camphor/kapoor during prayers. Easy to fill and clean. Brings divine atmosphere to your puja room. Ideal for gifting on festivals.',
    price: 592,
    originalPrice: 1499,
    finalPrice: 699,
    discount: 53,
    gstPercent: 18,
    stock: 55,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1605389659020-f5e93345e69e?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 267,
    featured: true,
  },
  {
    id: 'ld-002',
    name: 'Brass Peacock Kuthu Vilaku/Diya Antique Set of 2 Pcs',
    description: 'Stunning antique brass peacock-design kuthu vilaku (lamp) — set of 2. Intricate peacock motif representing beauty and grace. Antique finish gives a heritage aesthetic. Traditional South Indian oil lamp. Perfect for Diwali, weddings, and festive decorations. Suitable for home temple and living room display.',
    price: 2542,
    originalPrice: 3999,
    finalPrice: 2999,
    discount: 25,
    gstPercent: 18,
    stock: 20,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 189,
    featured: true,
  },
  {
    id: 'ld-003',
    name: 'Pure Brass Kuthu Vilaku/Diya (Kerala Fancy) Large Set of 2 Pcs',
    description: 'Grand Kerala-style brass kuthu vilaku set of 2 in large size (13 inch). Traditional stepped design popular in Kerala and Tamil Nadu. Heavy brass construction for stability. Perfect centrepiece for puja rooms and weddings. Deepens the spiritual atmosphere. Becomes more beautiful over time.',
    price: 4660,
    originalPrice: 6499,
    finalPrice: 5499,
    discount: 15,
    gstPercent: 18,
    stock: 12,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1605389659020-f5e93345e69e?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 78,
    featured: true,
  },
  {
    id: 'ld-004',
    name: 'Pure Brass Kuthu Vilaku/Diya (Kerala Fancy) Medium Set of 2 Pcs',
    description: 'Traditional Kerala-style brass kuthu vilaku in medium size (9 inch) — set of 2. Classic stepped design symbolising light and prosperity. Pure brass for authentic glow. Perfect for home temples, puja rooms, and festive decoration. Traditional oil lamp that creates a serene spiritual atmosphere.',
    price: 1949,
    originalPrice: 3499,
    finalPrice: 2299,
    discount: 34,
    gstPercent: 18,
    stock: 18,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 134,
    featured: false,
  },
  {
    id: 'ld-005',
    name: 'Pure Brass Kuthu Vilaku/Diya (Kerala Fancy) Small Set of 2 Pcs',
    description: 'Compact Kerala-style brass kuthu vilaku in small size (10 inch) — set of 2. Perfect for smaller puja spaces and gift-giving. Traditional stepped brass design. Can be used with oil or ghee. Polished finish that gleams beautifully when lit. A classic South Indian home essential.',
    price: 3305,
    originalPrice: 4999,
    finalPrice: 3899,
    discount: 22,
    gstPercent: 18,
    stock: 15,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1605389659020-f5e93345e69e?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 98,
    featured: false,
  },
  {
    id: 'ld-006',
    name: 'Pure Brass Lotus Stand Diya',
    description: 'Beautiful brass diya on a lotus-petal stand. The lotus symbolises purity, enlightenment, and divine grace. Intricate petal detailing around the base. Perfect for Diwali, Navratri, and daily puja. Can be used with oil or ghee. Makes an exquisite gift. Adds a divine ambience to any space.',
    price: 296,
    originalPrice: 699,
    finalPrice: 349,
    discount: 50,
    gstPercent: 18,
    stock: 75,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 312,
    featured: false,
  },
  {
    id: 'ld-007',
    name: 'Pure Brass Nandha Vilaku/Diya Set of 2 Pcs',
    description: 'Traditional pure brass Nandha vilaku (Nanda lamp) — set of 2. The Nandha lamp is kept eternally lit in temples as a symbol of the divine presence. Perfect for home temple use. Brass construction ensures longevity. Easy to fill with oil. A spiritually significant lamp for auspicious homes.',
    price: 508,
    originalPrice: 899,
    finalPrice: 599,
    discount: 33,
    gstPercent: 18,
    stock: 40,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1605389659020-f5e93345e69e?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 178,
    featured: false,
  },
  {
    id: 'ld-008',
    name: 'Pure Brass Sapthakanni Vilaku/Lamp/Diya',
    description: 'Sacred Sapthakanni brass lamp with seven wicks — an auspicious symbol of the seven divine mothers (Sapthamatrikas). Traditionally lit during Navratri and special prayers. Premium brass construction with detailed hand engravings. Seven wick holders for sevenfold blessings. A cherished puja room treasure.',
    price: 1016,
    originalPrice: 1799,
    finalPrice: 1199,
    discount: 33,
    gstPercent: 18,
    stock: 22,
    category: 'decor',
    subcategory: 'lamp-diya',
    material: 'Brass',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 134,
    featured: true,
  },
];

// ─── ORDERS (Demo data) ──────────────────────────────────────
export const orders: Order[] = [
  {
    id: 'ORD-001',
    customer: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    date: '2026-04-25',
    status: 'delivered',
    items: [
      { product: products[0], quantity: 1 },
      { product: products[3], quantity: 1 },
    ],
    subtotal: 1798,
    cgstAmount: 162,
    sgstAmount: 162,
    gstAmount: 324,
    total: 2122,
    address: '12, MG Road, Bangalore, Karnataka - 560001',
    paymentMethod: 'UPI',
  },
  {
    id: 'ORD-002',
    customer: 'Priya Mehta',
    email: 'priya.mehta@example.com',
    date: '2026-04-26',
    status: 'shipped',
    items: [
      { product: products[36], quantity: 1 },
    ],
    subtotal: 899,
    cgstAmount: 81,
    sgstAmount: 81,
    gstAmount: 162,
    total: 1061,
    address: '45, Andheri West, Mumbai, Maharashtra - 400058',
    paymentMethod: 'Card',
  },
  {
    id: 'ORD-003',
    customer: 'Amit Patel',
    email: 'amit.patel@example.com',
    date: '2026-04-27',
    status: 'processing',
    items: [
      { product: products[12], quantity: 2 },
    ],
    subtotal: 3798,
    cgstAmount: 342,
    sgstAmount: 342,
    gstAmount: 684,
    total: 4482,
    address: '78, CG Road, Ahmedabad, Gujarat - 380009',
    paymentMethod: 'COD',
  },
];

// ─── DASHBOARD STATS ─────────────────────────────────────────
export const dashboardStats = {
  totalRevenue: 1845230,
  totalOrders: 3847,
  totalProducts: products.length,
  totalCustomers: 12847,
  revenueGrowth: 18.5,
  ordersGrowth: 12.3,
  productsGrowth: 5.2,
  customersGrowth: 23.1,
};
